services:
  # Backend API Service
  - type: web
    name: multiplayer-snake-backend
    runtime: node
    rootDir: ./backend
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: FRONTEND_URL
        fromService:
          type: web
          name: multiplayer-snake-frontend
          property: host
    healthCheckPath: /health
    numInstances: 1
    plan: free

  # Frontend Static Site Service
  - type: web
    name: multiplayer-snake-frontend
    runtime: node
    rootDir: ./frontend
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
    healthCheckPath: /health
    numInstances: 1
    plan: free